[build]
builder = "NIXPACKS"
nixpacksPlan = """
providers = []

[phases.setup]
nixPkgs = ["nodejs_18", "python3", "make", "gcc-unwrapped"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = []
"""

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
