const EJERCICIOS = [
  // CHEST
  {grupo:'Chest',nombre:'Bench Press (Barbell)',musculos:'Chest, Triceps, Front Deltoid',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell + Bench'},
  {grupo:'Chest',nombre:'Bench Press (Dumbbell)',musculos:'Chest, Triceps, Stabilizers',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbells + Bench'},
  {grupo:'Chest',nombre:'Incline Bench Press (Barbell)',musculos:'Upper Chest, Front Deltoid',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell + Incline Bench'},
  {grupo:'Chest',nombre:'Incline Bench Press (Dumbbell)',musculos:'Upper Chest, Stabilizers',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbells + Incline Bench'},
  {grupo:'Chest',nombre:'Decline Bench Press (Barbell)',musculos:'Lower Chest, Triceps',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell + Decline Bench'},
  {grupo:'Chest',nombre:'Chest Fly (Dumbbell)',musculos:'Chest, Coracobrachialis',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells + Bench'},
  {grupo:'Chest',nombre:'Incline Fly (Dumbbell)',musculos:'Upper Chest, Front Deltoid',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells + Incline Bench'},
  {grupo:'Chest',nombre:'Cable Crossover',musculos:'Chest, Definition',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Chest',nombre:'Cable Fly (High to Low)',musculos:'Lower Chest',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Chest',nombre:'Cable Fly (Low to High)',musculos:'Upper Chest',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Chest',nombre:'Chest Dip',musculos:'Lower Chest, Triceps',tipo:'Compound',dificultad:'Intermediate',equipo:'Parallel Bars'},
  {grupo:'Chest',nombre:'Pec Deck Fly',musculos:'Chest, Final Contraction',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Chest',nombre:'Chest Press (Machine)',musculos:'Chest, Triceps',tipo:'Compound',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Chest',nombre:'Pull Over (Dumbbell)',musculos:'Chest, Serratus, Lat',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbell + Bench'},
  {grupo:'Chest',nombre:'Around the World',musculos:'Full Chest, Serratus',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells + Bench'},

  // BACK
  {grupo:'Back',nombre:'Deadlift (Barbell)',musculos:'Lower Back, Glutes, Hamstrings, Traps',tipo:'Compound',dificultad:'Advanced',equipo:'Barbell'},
  {grupo:'Back',nombre:'Romanian Deadlift (Barbell)',musculos:'Hamstrings, Glutes, Lower Back',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Back',nombre:'Romanian Deadlift (Dumbbell)',musculos:'Hamstrings, Glutes',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Back',nombre:'Sumo Deadlift',musculos:'Glutes, Adductors, Lower Back',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Back',nombre:'Pull Up (Overhand)',musculos:'Lat, Biceps, Rhomboids',tipo:'Compound',dificultad:'Intermediate',equipo:'Pull Up Bar'},
  {grupo:'Back',nombre:'Pull Up (Underhand)',musculos:'Lat, Biceps, Long Head',tipo:'Compound',dificultad:'Intermediate',equipo:'Pull Up Bar'},
  {grupo:'Back',nombre:'Pull Up (Neutral Grip)',musculos:'Lat, Brachialis, Rhomboids',tipo:'Compound',dificultad:'Intermediate',equipo:'Pull Up Bar'},
  {grupo:'Back',nombre:'Barbell Row (Overhand)',musculos:'Lat, Rhomboids, Biceps',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Back',nombre:'Barbell Row (Underhand)',musculos:'Lower Lat, Biceps',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Back',nombre:'Seated Row (Cable)',musculos:'Lat, Rhomboids, Biceps',tipo:'Compound',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Back',nombre:'Seated Wide-Grip Row (Cable)',musculos:'Rhomboids, Middle Traps',tipo:'Compound',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Back',nombre:'One-Arm Dumbbell Row',musculos:'Lat, Rhomboids, Biceps',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbell + Bench'},
  {grupo:'Back',nombre:'Lat Pulldown (Wide Grip)',musculos:'Lat, Biceps, Teres Major',tipo:'Compound',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Back',nombre:'Lat Pulldown (Narrow Grip)',musculos:'Lower Lat, Biceps',tipo:'Compound',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Back',nombre:'Lat Pulldown (Neutral Grip)',musculos:'Lat, Brachialis',tipo:'Compound',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Back',nombre:'Straight Arm Pulldown',musculos:'Lat, Serratus',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Back',nombre:'Back Extension',musculos:'Lower Back, Glutes',tipo:'Isolation',dificultad:'Beginner',equipo:'Hyperextension Bench'},
  {grupo:'Back',nombre:'Back Extension (Machine)',musculos:'Lower Back',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Back',nombre:'Good Morning (Barbell)',musculos:'Lower Back, Hamstrings, Glutes',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Back',nombre:'Shrug (Barbell)',musculos:'Upper Traps',tipo:'Isolation',dificultad:'Beginner',equipo:'Barbell'},
  {grupo:'Back',nombre:'Shrug (Dumbbell)',musculos:'Upper Traps',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Back',nombre:'Face Pull',musculos:'Rear Deltoid, Rhomboids, Rotator Cuff',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},

  // SHOULDERS
  {grupo:'Shoulders',nombre:'Overhead Press (Barbell)',musculos:'Front & Middle Deltoid, Triceps',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Shoulders',nombre:'Seated Overhead Press (Barbell)',musculos:'Deltoids, Triceps, Traps',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Shoulders',nombre:'Seated Dumbbell Press',musculos:'Deltoids, Triceps',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbells + Bench'},
  {grupo:'Shoulders',nombre:'Standing Dumbbell Press',musculos:'Deltoids, Triceps, Core',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Shoulders',nombre:'Arnold Press',musculos:'Full Deltoid, Triceps',tipo:'Compound',dificultad:'Intermediate',equipo:'Dumbbells + Bench'},
  {grupo:'Shoulders',nombre:'Lateral Raise (Dumbbell)',musculos:'Middle Deltoid',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Shoulders',nombre:'Lateral Raise (Cable)',musculos:'Middle Deltoid, Constant Tension',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Shoulders',nombre:'Front Raise (Barbell)',musculos:'Front Deltoid',tipo:'Isolation',dificultad:'Beginner',equipo:'Barbell'},
  {grupo:'Shoulders',nombre:'Front Raise (Dumbbell)',musculos:'Front Deltoid',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Shoulders',nombre:'Reverse Fly (Dumbbell)',musculos:'Rear Deltoid, Rhomboids',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Shoulders',nombre:'Reverse Fly (Cable)',musculos:'Rear Deltoid, Constant Tension',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Shoulders',nombre:'Shoulder Press (Machine)',musculos:'Deltoids, Triceps',tipo:'Compound',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Shoulders',nombre:'Upright Row (Barbell)',musculos:'Middle Deltoid, Traps',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Shoulders',nombre:'External Rotation (Cable)',musculos:'Infraspinatus, Rotator Cuff',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},

  // BICEPS
  {grupo:'Biceps',nombre:'Barbell Curl',musculos:'Biceps Brachii, Brachioradialis',tipo:'Isolation',dificultad:'Beginner',equipo:'Barbell'},
  {grupo:'Biceps',nombre:'EZ Bar Curl',musculos:'Biceps Brachii, Less Wrist Strain',tipo:'Isolation',dificultad:'Beginner',equipo:'EZ Bar'},
  {grupo:'Biceps',nombre:'Alternating Dumbbell Curl',musculos:'Biceps Brachii, Supinator',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Biceps',nombre:'Simultaneous Dumbbell Curl',musculos:'Biceps Brachii Bilateral',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Biceps',nombre:'Hammer Curl (Dumbbell)',musculos:'Brachioradialis, Brachialis',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Biceps',nombre:'Hammer Curl (Cable)',musculos:'Brachioradialis, Constant Tension',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Biceps',nombre:'Concentration Curl',musculos:'Biceps Brachii, Peak',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbell'},
  {grupo:'Biceps',nombre:'Preacher Curl (Barbell)',musculos:'Biceps Short Head',tipo:'Isolation',dificultad:'Beginner',equipo:'Preacher Bench + Barbell'},
  {grupo:'Biceps',nombre:'Preacher Curl (Dumbbell)',musculos:'Biceps Short Head, Isolated',tipo:'Isolation',dificultad:'Beginner',equipo:'Preacher Bench + Dumbbell'},
  {grupo:'Biceps',nombre:'Cable Curl',musculos:'Biceps Brachii, Constant Tension',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Biceps',nombre:'Incline Dumbbell Curl',musculos:'Biceps Long Head, Stretch',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells + Incline Bench'},
  {grupo:'Biceps',nombre:'Bicep Curl (Machine)',musculos:'Biceps Brachii',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},

  // TRICEPS
  {grupo:'Triceps',nombre:'Skull Crusher (Barbell)',musculos:'Triceps Long & Lateral Head',tipo:'Isolation',dificultad:'Intermediate',equipo:'Barbell + Bench'},
  {grupo:'Triceps',nombre:'Skull Crusher (EZ Bar)',musculos:'Triceps, Less Wrist Strain',tipo:'Isolation',dificultad:'Beginner',equipo:'EZ Bar + Bench'},
  {grupo:'Triceps',nombre:'Skull Crusher (Dumbbell)',musculos:'Triceps Long Head',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbells + Bench'},
  {grupo:'Triceps',nombre:'Tricep Pushdown (Rope)',musculos:'Triceps Lateral Head',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Triceps',nombre:'Tricep Pushdown (Bar)',musculos:'Triceps Lateral Head',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Triceps',nombre:'Overhead Tricep Extension (Cable)',musculos:'Triceps Long Head',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Triceps',nombre:'Bench Dip',musculos:'Triceps, Lower Chest',tipo:'Compound',dificultad:'Beginner',equipo:'Bench'},
  {grupo:'Triceps',nombre:'Tricep Dip',musculos:'Triceps, Upright Torso',tipo:'Compound',dificultad:'Intermediate',equipo:'Parallel Bars'},
  {grupo:'Triceps',nombre:'Close Grip Bench Press',musculos:'Triceps, Chest, Front Deltoid',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell + Bench'},
  {grupo:'Triceps',nombre:'Tricep Kickback (Dumbbell)',musculos:'Triceps Long Head, Contraction',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbell'},
  {grupo:'Triceps',nombre:'Overhead Extension (Dumbbell)',musculos:'Triceps Long Head, Stretch',tipo:'Isolation',dificultad:'Beginner',equipo:'Dumbbell'},
  {grupo:'Triceps',nombre:'Overhead Extension (Cable)',musculos:'Triceps Long Head',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},

  // LEGS
  {grupo:'Legs',nombre:'Squat (Barbell)',musculos:'Quadriceps, Glutes, Hamstrings, Core',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Legs',nombre:'Front Squat (Barbell)',musculos:'Quadriceps, Glutes, Core',tipo:'Compound',dificultad:'Advanced',equipo:'Barbell'},
  {grupo:'Legs',nombre:'Goblet Squat (Dumbbell)',musculos:'Quadriceps, Glutes',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbell'},
  {grupo:'Legs',nombre:'Bulgarian Split Squat (Dumbbell)',musculos:'Quadriceps, Glutes, Balance',tipo:'Compound',dificultad:'Intermediate',equipo:'Dumbbells + Bench'},
  {grupo:'Legs',nombre:'Bulgarian Split Squat (Barbell)',musculos:'Quadriceps, Glutes',tipo:'Compound',dificultad:'Advanced',equipo:'Barbell + Bench'},
  {grupo:'Legs',nombre:'Leg Press',musculos:'Quadriceps, Glutes, Hamstrings',tipo:'Compound',dificultad:'Beginner',equipo:'Leg Press Machine'},
  {grupo:'Legs',nombre:'Hack Squat (Machine)',musculos:'Quadriceps, Glutes',tipo:'Compound',dificultad:'Intermediate',equipo:'Hack Squat Machine'},
  {grupo:'Legs',nombre:'Leg Extension (Machine)',musculos:'Quadriceps',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Legs',nombre:'Lying Leg Curl (Machine)',musculos:'Hamstrings',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Legs',nombre:'Seated Leg Curl (Machine)',musculos:'Hamstrings Short Head',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Legs',nombre:'Hip Thrust (Barbell)',musculos:'Glutes, Hamstrings',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell + Bench'},
  {grupo:'Legs',nombre:'Hip Thrust (Dumbbell)',musculos:'Glutes',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbell + Bench'},
  {grupo:'Legs',nombre:'Glute Bridge',musculos:'Glutes, Hamstrings',tipo:'Compound',dificultad:'Beginner',equipo:'Bodyweight'},
  {grupo:'Legs',nombre:'Walking Lunge (Dumbbell)',musculos:'Quadriceps, Glutes, Balance',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbells'},
  {grupo:'Legs',nombre:'Static Lunge (Barbell)',musculos:'Quadriceps, Glutes',tipo:'Compound',dificultad:'Intermediate',equipo:'Barbell'},
  {grupo:'Legs',nombre:'Side Lunge (Dumbbell)',musculos:'Adductors, Glutes, Quadriceps',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbell'},
  {grupo:'Legs',nombre:'Standing Calf Raise (Machine)',musculos:'Gastrocnemius',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Legs',nombre:'Seated Calf Raise (Plate Loaded)',musculos:'Soleus',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Legs',nombre:'Calf Raise on Leg Press',musculos:'Gastrocnemius, Soleus',tipo:'Isolation',dificultad:'Beginner',equipo:'Leg Press Machine'},
  {grupo:'Legs',nombre:'Hip Adductor (Machine)',musculos:'Hip Adductors',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Legs',nombre:'Hip Abductor (Machine)',musculos:'Abductors, Glute Med',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Legs',nombre:'Cable Glute Kickback',musculos:'Glute Max, Isolation',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Legs',nombre:'Step Up (Dumbbell)',musculos:'Quadriceps, Glutes, Balance',tipo:'Compound',dificultad:'Beginner',equipo:'Dumbbells + Bench'},

  // ABS
  {grupo:'Abs',nombre:'Crunch',musculos:'Rectus Abdominis',tipo:'Isolation',dificultad:'Beginner',equipo:'Bodyweight'},
  {grupo:'Abs',nombre:'Cable Crunch',musculos:'Rectus Abdominis, Resistance',tipo:'Isolation',dificultad:'Beginner',equipo:'Cable Machine'},
  {grupo:'Abs',nombre:'Crunch (Machine)',musculos:'Rectus Abdominis',tipo:'Isolation',dificultad:'Beginner',equipo:'Machine'},
  {grupo:'Abs',nombre:'Plank',musculos:'Full Core, Transverse Abs',tipo:'Stabilization',dificultad:'Beginner',equipo:'Bodyweight'},
  {grupo:'Abs',nombre:'Side Plank',musculos:'Obliques, Lateral Core',tipo:'Stabilization',dificultad:'Beginner',equipo:'Bodyweight'},
  {grupo:'Abs',nombre:'Hanging Leg Raise',musculos:'Lower Abs, Hip Flexors',tipo:'Isolation',dificultad:'Intermediate',equipo:'Pull Up Bar'},
  {grupo:'Abs',nombre:'Hanging Knee Raise',musculos:'Lower Abs, Hip Flexors',tipo:'Isolation',dificultad:'Beginner',equipo:'Pull Up Bar'},
  {grupo:'Abs',nombre:'Ab Rollout',musculos:'Full Core, Lats',tipo:'Compound',dificultad:'Advanced',equipo:'Ab Wheel'},
  {grupo:'Abs',nombre:'Russian Twist (Plate)',musculos:'Obliques, Rectus Abdominis',tipo:'Isolation',dificultad:'Beginner',equipo:'Plate'},
  {grupo:'Abs',nombre:'Scissors',musculos:'Lower Abs, Hip Flexors',tipo:'Isolation',dificultad:'Beginner',equipo:'Bodyweight'},
  {grupo:'Abs',nombre:'Mountain Climber',musculos:'Core, Cardio, Shoulders',tipo:'Compound',dificultad:'Beginner',equipo:'Bodyweight'},
  {grupo:'Abs',nombre:'Dead Bug',musculos:'Transverse Abs, Stabilizers',tipo:'Stabilization',dificultad:'Beginner',equipo:'Bodyweight'},
  {grupo:'Abs',nombre:'Oblique Crunch',musculos:'Internal & External Obliques',tipo:'Isolation',dificultad:'Beginner',equipo:'Bodyweight'},
  {grupo:'Abs',nombre:'Leg Raise (Flat Bench)',musculos:'Lower Abs',tipo:'Isolation',dificultad:'Beginner',equipo:'Bench'},
];

const ALIMENTOS = [
  {categoria:'Protein',nombre:'Chicken Breast',calorias:165,proteinas:31,carbos:0,grasas:3.6},
  {categoria:'Protein',nombre:'Chicken Thigh (skinless)',calorias:177,proteinas:25,carbos:0,grasas:8.2},
  {categoria:'Protein',nombre:'Turkey Breast',calorias:135,proteinas:30,carbos:0,grasas:1},
  {categoria:'Protein',nombre:'Lean Ground Beef (95%)',calorias:150,proteinas:27,carbos:0,grasas:4.5},
  {categoria:'Protein',nombre:'Beef Tenderloin',calorias:158,proteinas:29,carbos:0,grasas:4.3},
  {categoria:'Protein',nombre:'Pork Loin',calorias:143,proteinas:27,carbos:0,grasas:3.5},
  {categoria:'Protein',nombre:'Salmon (fresh)',calorias:208,proteinas:20,carbos:0,grasas:13},
  {categoria:'Protein',nombre:'Hake',calorias:86,proteinas:17,carbos:0,grasas:1.4},
  {categoria:'Protein',nombre:'Cod (fresh)',calorias:82,proteinas:18,carbos:0,grasas:0.7},
  {categoria:'Protein',nombre:'Tuna (canned in water)',calorias:116,proteinas:26,carbos:0,grasas:1},
  {categoria:'Protein',nombre:'Shrimp (cooked)',calorias:99,proteinas:21,carbos:0,grasas:1.1},
  {categoria:'Protein',nombre:'Whole Eggs (L)',calorias:143,proteinas:13,carbos:1,grasas:10},
  {categoria:'Protein',nombre:'Egg Whites',calorias:52,proteinas:11,carbos:0.7,grasas:0.2},
  {categoria:'Protein',nombre:'Whey Isolate',calorias:110,proteinas:26,carbos:1,grasas:0.5},
  {categoria:'Protein',nombre:'Whey Concentrate',calorias:120,proteinas:24,carbos:4,grasas:2},
  {categoria:'Protein',nombre:'Casein Protein',calorias:118,proteinas:24,carbos:3,grasas:1.5},
  {categoria:'Dairy',nombre:'Greek Yogurt 0%',calorias:59,proteinas:10,carbos:3.6,grasas:0.4},
  {categoria:'Dairy',nombre:'Cottage Cheese',calorias:98,proteinas:11,carbos:3.4,grasas:4.5},
  {categoria:'Dairy',nombre:'Semi-skimmed Milk',calorias:46,proteinas:3.3,carbos:4.7,grasas:1.6},
  {categoria:'Dairy',nombre:'Parmesan Cheese',calorias:431,proteinas:38,carbos:4,grasas:29},
  {categoria:'Dairy',nombre:'Mozzarella Light',calorias:190,proteinas:19,carbos:2,grasas:12},
  {categoria:'Carbs',nombre:'White Rice',calorias:365,proteinas:7,carbos:80,grasas:0.7},
  {categoria:'Carbs',nombre:'Brown Rice',calorias:350,proteinas:7.5,carbos:73,grasas:2.7},
  {categoria:'Carbs',nombre:'Oats',calorias:389,proteinas:17,carbos:66,grasas:7},
  {categoria:'Carbs',nombre:'Potato (boiled)',calorias:77,proteinas:2,carbos:17,grasas:0.1},
  {categoria:'Carbs',nombre:'Sweet Potato (boiled)',calorias:86,proteinas:1.6,carbos:20,grasas:0.1},
  {categoria:'Carbs',nombre:'Pasta (dry)',calorias:370,proteinas:12,carbos:75,grasas:1.5},
  {categoria:'Carbs',nombre:'Whole Grain Bread',calorias:247,proteinas:9,carbos:41,grasas:3.4},
  {categoria:'Carbs',nombre:'Quinoa (cooked)',calorias:120,proteinas:4.4,carbos:21,grasas:1.9},
  {categoria:'Carbs',nombre:'Banana',calorias:89,proteinas:1.1,carbos:23,grasas:0.3},
  {categoria:'Carbs',nombre:'Apple',calorias:52,proteinas:0.3,carbos:14,grasas:0.2},
  {categoria:'Carbs',nombre:'Orange',calorias:47,proteinas:0.9,carbos:12,grasas:0.1},
  {categoria:'Carbs',nombre:'Strawberries',calorias:32,proteinas:0.7,carbos:7.7,grasas:0.3},
  {categoria:'Carbs',nombre:'Blueberries',calorias:57,proteinas:0.7,carbos:14,grasas:0.3},
  {categoria:'Carbs',nombre:'Lentils (cooked)',calorias:116,proteinas:9,carbos:20,grasas:0.4},
  {categoria:'Carbs',nombre:'Chickpeas (cooked)',calorias:164,proteinas:8.9,carbos:27,grasas:2.6},
  {categoria:'Vegetables',nombre:'Broccoli',calorias:34,proteinas:2.8,carbos:7,grasas:0.4},
  {categoria:'Vegetables',nombre:'Spinach',calorias:23,proteinas:2.9,carbos:3.6,grasas:0.4},
  {categoria:'Vegetables',nombre:'Mixed Salad',calorias:15,proteinas:1.4,carbos:2.8,grasas:0.2},
  {categoria:'Vegetables',nombre:'Tomato',calorias:18,proteinas:0.9,carbos:3.9,grasas:0.2},
  {categoria:'Vegetables',nombre:'Cucumber',calorias:16,proteinas:0.7,carbos:3.6,grasas:0.1},
  {categoria:'Vegetables',nombre:'Red Bell Pepper',calorias:31,proteinas:1,carbos:6,grasas:0.3},
  {categoria:'Vegetables',nombre:'Asparagus',calorias:20,proteinas:2.2,carbos:3.9,grasas:0.1},
  {categoria:'Vegetables',nombre:'Mushrooms',calorias:22,proteinas:3.1,carbos:3.3,grasas:0.3},
  {categoria:'Vegetables',nombre:'Zucchini',calorias:17,proteinas:1.2,carbos:3.1,grasas:0.3},
  {categoria:'Vegetables',nombre:'Green Beans',calorias:31,proteinas:1.8,carbos:7,grasas:0.2},
  {categoria:'Vegetables',nombre:'Cauliflower',calorias:25,proteinas:1.9,carbos:5,grasas:0.3},
  {categoria:'Vegetables',nombre:'Kale',calorias:49,proteinas:4.3,carbos:9,grasas:0.9},
  {categoria:'Healthy Fats',nombre:'Extra Virgin Olive Oil',calorias:884,proteinas:0,carbos:0,grasas:100},
  {categoria:'Healthy Fats',nombre:'Avocado',calorias:160,proteinas:2,carbos:9,grasas:15},
  {categoria:'Healthy Fats',nombre:'Raw Almonds',calorias:579,proteinas:21,carbos:22,grasas:50},
  {categoria:'Healthy Fats',nombre:'Walnuts',calorias:654,proteinas:15,carbos:14,grasas:65},
  {categoria:'Healthy Fats',nombre:'Natural Peanut Butter',calorias:588,proteinas:25,carbos:20,grasas:50},
  {categoria:'Healthy Fats',nombre:'Chia Seeds',calorias:486,proteinas:17,carbos:42,grasas:31},
];

module.exports = { EJERCICIOS, ALIMENTOS };
